### ISSUE TITLE
10 Day Forcast will not load

### ISSUE THREAD

**Issue by nountaineer** [alexis-jaksone/forecast-plus#3]
It appears that I am not the only one who can not access the 10 day forecast. This issue has existed for some time now.

**Comment by alexis-jaksone** [comment]
Are you sure you are on the latest release?

**Comment by nountaineer** [comment]
The last update was 1-28-2016. It is the icon on the toolbar that tries to load the 10 day forecast but does not succeed when activated in Firefox. 

----- Original Message -----

**Comment by alexis-jaksone** [comment]
Can you confirm the problem on a clean profile?
http://blog.add0n.com/2016/01/30/how-to-use-firefox-profile-manager.html

I cannot reproduce it, so maybe there is a conflict with another extensions of yours.

**Comment by Kim-Maidment** [comment]
I have exactly the same problem on Firefox. it just stopped working! Would also be a good idea to have a full page icon so I can see everything together. Thank you

**Comment by Kim-Maidment** [comment]
Have also noted that the 'settings' don't work either and I can't change the location. In fact quite a lot is missing.

**Comment by alexis-jaksone** [comment]
@Kim-Maidment I assume you are on Firefox right? Have you tried the extension on a clean profile? If you cannot set settings, definitely there is something wrong with your current profile.

**Comment by Kim-Maidment** [comment]
I tried to run   firefox.exe –P but it comes up with a message "windows cannot find firefox.exe". It must be there because I use Firefox every day!

**Comment by alexis-jaksone** [comment]
How about:

``` bash
"C:\Program Files (x86)\Mozilla Firefox\firefox.exe" -P
```

or

``` bash
"C:\Program Files\Mozilla Firefox\firefox.exe" -P
```

**Comment by Kim-Maidment** [comment]
"C:\Program Files (x86)\Mozilla Firefox\firefox.exe" -P worked, I set up a clean profile and it worked. I suspect I have something corrupted somewhere. I did uninstall Forecast-plus, switched PC off then re-installed it but it didn't make any difference. Must be a setup file left on the computer. Do you know which one it is please? I do love this system because there is a station about a quarter of a mile from me. Would be a good idea to be able to switch to Full Page.

**Comment by alexis-jaksone** [comment]
So the extension works fine on the clean profile but you need to get back to the old one?

**Comment by Kim-Maidment** [comment]
Hello Alexis, yes that is right, the new profile runs fine. I can change to another weather station, the forecast works and everything is good. I would like to keep the 'old' profile because it is all set up for me. I didn't mess with the settings before it went off, it just stopped working.
Did you get a reply from Mountaineer? Thanks.

**Comment by alexis-jaksone** [comment]
Okay then, go to the old profile. Open "about:config" in a new tab. Search for `extensions.jid1-w3xH9kJhd3KJUp@jetpack.` and reset all preferences by right clicking on each of them. These are all preferences related to this extension. This might help fixing the problem.

**Comment by Kim-Maidment** [comment]
Hello Alexis, did the above and no joy, all it did was moved my location. I then removed Forecast Plus from the extensions, deleted all files relating to the program from  ;C:...................AppData\Roaming\Mozilla\Firefox\Profiles\cgr8xgr9.default\extensions. Restarted Firefox then opened; C...................AppData\Roaming\Mozilla\Firefox\Profiles\cgr8xgr9.default\extensions and copied the jid1-w3xH9kJhd3KJUp@jetpack.xpi File from the Clean profile to the default one and this made no difference. Could it be an update in Firefox that has caused a problem? I have it on automatic update. Thanks for trying.

**Comment by alexis-jaksone** [comment]
If the extension works fine on a clean profile, there are  few possibilities:
1. You have an extension or ad-blocker that blocks some resources required by extension to load those sections.
2. Your Firefox profile is somehow damaged.

You just need to play around and see if you can fix your Firefox profile. Please share here if you got a solution.

**Comment by justinzane** [comment]
Confirmed that there is a problem on 47.0a. Using Adblock Plus, noscript. Best option for those of us with issues would be for an option to view forecast in a full tab, not simply a panel; since we are likely familiar with debugging full tabs. Other help would be instructions for debugging the panel itself.

**Comment by Kim-Maidment** [comment]
That is interesting Justin. I have Ghostery on my browser which stops trackers. On this forum it is stopping Google Analytics so I should look in to that. No that didn't make any difference! At least I know it is not that. I don't use Adblock plus. I just looked at my Browser add-ons and I have Location Guard but disabled that and it made no difference. I also use Forcastfox, this used to have a problem but they have brought out a new version and that is OK. I am a Scuba Diver so both weather add-ons are good for me!

**Comment by alexis-jaksone** [comment]
Please re-open if you are still experiencing this issue

**Comment by Kim-Maidment** [comment]
Hi, yes still have the same problem. I have been using a different weather forecast add on so had actually forgotten about this one although it is better as it has local input.

**Comment by alexis-jaksone** [comment]
You need to make sure your blocker extensions are not blocking the required resources. You can confirm this by disabling them temporary.
